// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqvafezledonlsgjivke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxdmFmZXpsZWRvbmxzZ2ppdmtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIzNzkxMTAsImV4cCI6MjA4Nzk1NTExMH0.RSJRwPWMCEJux-7_NqxpyroF9JACI25x3zqmsYAcrRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});